---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taruncapstone1
  namespace: default
  labels:
    app: taruncapstone1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: taruncapstone1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taruncapstone1
    spec:
      containers:
        - name: taruncapstone1
          image: tarungirdhar1980/taruncapstone1
          imagePullPolicy: Always
          name: taruncapstone1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "taruncapstone-lb"
spec:
  type: LoadBalancer
  selector:
    app: taruncapstone1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
